defaults:
  - /training/base_training@_global_.training

dataset_name: books3
tokenizer_name: Qwen/Qwen2.5-0.5B

total_steps: 300
ilr_warmup_steps: 0
optimizer_outer:
  optimizer_type: adamw
  b1: 0.9
  b2: 0.95
  clip_gradient: 1.0
  end_lr: 1e-05
  init_lr: 0.0
  lr: 4e-04
  lr_decay_steps: 300
  lr_warmup_steps: 30
  weight_decay: 0.1
