defaults:
  - base_model

name: smollm2_360m
vocab_size: 49152
output_size: 49152
bos_token_id: 0
eos_token_id: 0
num_hidden_layers: 32
hidden_size: 960
num_attention_heads: 15
num_key_value_heads: 5
intermediate_size: 2560
initializer_range: 0.02
rms_norm_eps: 1e-5
tie_word_embeddings: True
rope_theta: 100000
seq_len: 32768
attention_pattern: full
